### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by drewdun81** [aschenbrenera/OneDND_Collation#1]
Near the top of page 15 it says "the iconic Ranger is a thief," when you meant to describe the Rogue.

**Comment by aschenbrenera** [comment]
Thank you. This has been corrected for the next release.

**Comment by drewdun81** [comment]
Similarly, you wrote Ranger when you meant to write Rogue, this time on the bottom page 14.
![Screen Shot 2022-10-09 at 3 01 28 PM](https://user-images.githubusercontent.com/115278008/194774810-5a8d2ed7-6934-41f4-962c-0ace43094a2e.png)
